services:
  db:
    container_name: postgres
    image: postgres:16.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fb-oracle-db
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped

  sonarqube_db:
    container_name: sonarqube_db
    image: postgres:16.3
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonarqube
      PGDATA: /data/sonarqube
    volumes:
      - sonarqube_db:/data/sonarqube
    ports:
      - "5433:5432"  # Exposing different port to avoid conflict
    networks:
      - db
    restart: unless-stopped

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube_db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
    depends_on:
      - sonarqube_db
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    networks:
      - db
    restart: unless-stopped

  football-oracle-backend:
    container_name: football-oracle-backend
    image: sshaikholla/football-oracle-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/fb-oracle-db
      SPRING_DATASOURCE_USERNAME: {{}}
      SPRING_DATASOURCE_PASSWORD: {{}}
      GOOGLE_CLOUD_PROJECT_ID: {{}}
      GOOGLE_CLOUD_REGION: {{}}
      JWT_SECRET: {{}}
    ports:
      - "8080:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped

  football-oracle-frontend:
    container_name: football-oracle-frontend
    image: sshaikholla/football-oracle-frontend
    build:
      context: frontend/football-oracle-fe
      args:
        api_base_url: http://football-oracle-backend:8080
    environment:
      - VITE_API_BASE_URL=http://localhost:8080
    ports:
      - "3000:5173"
    depends_on:
      - football-oracle-backend
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
  sonarqube_db:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: