@startuml
left to right direction

actor Guest as g
actor RegisteredUser as ru
actor Admin as a

package "Football Oracle System" {
    usecase "Access registration page" as UC1
    usecase "Fill in registration details and submit" as UC2
    usecase "Create new user account" as UC3
    usecase "Log in using registered credentials" as UC4
    usecase "Enter player’s name in search bar" as UC5
    usecase "Display list of players matching search criteria" as UC6
    usecase "Select player from search results" as UC7
    usecase "Display scouting report for selected player" as UC8
    usecase "View scouting report" as UC9
    usecase "Submit rating and/or review" as UC10
    usecase "Update report with user’s feedback" as UC11
    usecase "Access profile management page" as UC12
    usecase "Update personal information or reviews" as UC13
    usecase "Save updated information" as UC14
    usecase "Access user management page" as UC15
    usecase "View and update user information" as UC16
    usecase "Disable or delete user accounts" as UC17
}

g --> UC1
g --> UC2
UC2 --> UC3
g --> UC4

ru --> UC5
g --> UC5
UC5 --> UC6

ru --> UC7
g --> UC7
UC7 --> UC8

ru --> UC9
ru --> UC10
UC10 --> UC11

ru --> UC12
ru --> UC13
UC13 --> UC14

a --> UC15
a --> UC16
a --> UC17
@enduml