server:
  port: 8080
  error:
    include-message: always

jwt:
    secret: "foobar_123456789_batman_123456789_ironman_123456789"

google:
  cloud:
    project-id: "gen-lang-client-0946890480"
    region: "europe-west3"

cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"

management:
    endpoints:
        web:
        exposure:
            include: "health, info"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.oracle.football: DEBUG
  file:
    name: logs/app.log


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fb-oracle-db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB
