spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  main:
    web-application-type: servlet
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
  codec:
    max-in-memory-size: 10MB

server:
  port: 8080
  error:
    include-message: always

jwt:
  secret: ${JWT_SECRET}

google:
  cloud:
    project-id: ${GOOGLE_CLOUD_PROJECT_ID}
    region: ${GOOGLE_CLOUD_REGION}

cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "*"

management:
    endpoints:
        web:
        exposure:
            include: "health, info"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    com.oracle.football: DEBUG
  file:
    name: logs/app.log